### ISSUE TITLE
Non verified code,Why!!

### ISSUE THREAD

**Issue by shokry-suleiman** [workshopper/how-to-markdown#59] opened 2017-07-01 11:23 UTC
# Lists

- One
  - 1.1
  - 1.2
- Two
  - 2.1
  - 2.2
- Three
- Four
- Five

**Comment by shokry-suleiman** [comment] 2017-07-01 11:46
@denysdovhan

**Comment by itzsaga** [comment] 2017-07-01 22:28
Not sure what you're asking @shokry-suleiman

**Comment by shokry-suleiman** [comment] 2017-07-02 14:48
Hi @itzsaga  
I have made correct solution to this challenge.
but it dose not  complete. 
Lists Challenge

**Comment by itzsaga** [comment] 2017-07-02 20:17
Can you paste the code for your solution and the error you're getting, please?

**Comment by shokry-suleiman** [comment] 2017-07-03 10:17
Oky

**Comment by itzsaga** [comment] 2017-10-04 00:42
Closing this since it's been 3 months. If there's still a reproducible issue let us know.

**Closed as completed by itzsaga** 2017-10-04 00:42 UTC
